# Generated by Django 2.1.4 on 2018-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='description', max_length=3000),
            preserve_default=False,
        ),
    ]
